source 'https://rubygems.org'
ruby '2.0.0'

gem 'coffee-rails', '~> 3.2.1'
gem 'compass-rails'
gem 'jquery-rails'
gem 'rails', '3.2.13'
gem 'rails_12factor'
gem 'sass-rails', '~> 3.2.3'
gem 'uglifier', '>= 1.0.3'
gem 'therubyracer'